export const COMMAND_SHOW_GITMOJI = "mini-tool.showGitmoji"
export const COMMAND_ADD_REGION_TO_SELECTION = "mini-tool.addRegionToSelection"
export const COMMAND_ADD_CSS_PX_IGNORE = "mini-tool.addCssPxIgnore"
export const COMMAND_NEW_FILE = "mini-tool.newFile"
export const COMMAND_OPEN_WEBVIEW = "mini-tool.openWebview"
export const COMMAND_DOT_LOG = "mini-tool.dotLog"
export const COMMAND_CHINESE_FORMAT = "mini-tool.chineseFormat"
export const COMMAND_CODE_SNAP = "mini-tool.codeSnap"
